src/Entity/Meal.php
<?php

namespace App\Entity;

use App\Repository\MealRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

#[ORM\Entity(repositoryClass: MealRepository::class)]
class Meal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 50)]
    private ?string $category = null;

    #[ORM\Column]
    private ?int $calories = null;

    #[ORM\Column]
    private ?float $rating = null;

    #[ORM\Column(length: 1000)]
    private ?string $preparation = null;

    #[ORM\Column]
    private ?int $cooking_time = null;

    #[ORM\OneToMany(mappedBy: 'fk_monday', targetEntity: Week::class)]
    private Collection $weeks;

    #[ORM\OneToMany(mappedBy: 'fk_meal', targetEntity: IngredientMeal::class)]
    private Collection $ingredientMeals;

    #[ORM\ManyToOne(inversedBy: 'meals')]
    #[ORM\JoinColumn(onDelete: 'set null')]
    private ?User $fk_user = null;

    #[ORM\Column]
    private ?bool $approved = null;

    #[ORM\Column(length: 1000)]
    private ?string $Ingredients = null;

    public function __construct()
    {
        $this->weeks = new ArrayCollection();
        $this->ingredientMeals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCalories(): ?int
    {
        return $this->calories;
    }

    public function setCalories(int $calories): self
    {
        $this->calories = $calories;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(float $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getPreparation(): ?string
    {
        return $this->preparation;
    }

    public function setPreparation(string $preparation): self
    {
        $this->preparation = $preparation;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cooking_time;
    }

    public function setCookingTime(int $cooking_time): self
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    /**
     * @return Collection<int, Week>
     */
    public function getWeeks(): Collection
    {
        return $this->weeks;
    }

    public function addWeek(Week $week): self
    {
        if (!$this->weeks->contains($week)) {
            $this->weeks->add($week);
            $week->setFkMonday($this);
        }

        return $this;
    }

    public function removeWeek(Week $week): self
    {
        if ($this->weeks->removeElement($week)) {
            // set the owning side to null (unless already changed)
            if ($week->getFkMonday() === $this) {
                $week->setFkMonday(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, IngredientMeal>
     */
    public function getIngredientMeals(): Collection
    {
        return $this->ingredientMeals;
    }

    public function addIngredientMeal(IngredientMeal $ingredientMeal): self
    {
        if (!$this->ingredientMeals->contains($ingredientMeal)) {
            $this->ingredientMeals->add($ingredientMeal);
            $ingredientMeal->setFkMeal($this);
        }

        return $this;
    }

    public function removeIngredientMeal(IngredientMeal $ingredientMeal): self
    {
        if ($this->ingredientMeals->removeElement($ingredientMeal)) {
            // set the owning side to null (unless already changed)
            if ($ingredientMeal->getFkMeal() === $this) {
                $ingredientMeal->setFkMeal(null);
            }
        }

        return $this;
    }

    public function getFkUser(): ?User
    {
        return $this->fk_user;
    }

    public function setFkUser(?User $fk_user): self
    {
        $this->fk_user = $fk_user;

        return $this;
    }

    public function isApproved(): ?bool
    {
        return $this->approved;
    }

    public function setApproved(bool $approved): self
    {
        $this->approved = $approved;

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->Ingredients;
    }

    public function setIngredients(string $Ingredients): self
    {
        $this->Ingredients = $Ingredients;

        return $this;
    }
}

src/Controller/MealUserController.php
<?php

namespace App\Controller;

use App\Entity\Meal;
use App\Form\Meal1Type;
use App\Repository\MealRepository;
use App\Service\FileUploader;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user/meal')]
class MealUserController extends AbstractController
{
    #[Route('/', name: 'app_meal_user_index', methods: ['GET'])]
    public function index(MealRepository $mealRepository): Response
    {
        return $this->render('meal_user/index.html.twig', [
            'meals' => $mealRepository->findBy(["fk_user" => $this->getUser(), 'approved' => 1]),
        ]);
    }

    #[Route('/new', name: 'app_meal_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MealRepository $mealRepository, FileUploader $fileUploader): Response
    {
        $meal = new Meal();
        $form = $this->createForm(Meal1Type::class, $meal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $meal->setApproved(0);
            $meal->setFkUser($this->getUser());
            $image = $form->get('picture')->getData();
            if ($image) {
                $imageName = $fileUploader->upload($image);
                $meal->setPicture($imageName);
            }

            $mealRepository->save($meal, true);

            return $this->redirectToRoute('app_meal_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('meal_user/new.html.twig', [
            'meal' => $meal,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_meal_user_show', methods: ['GET'])]
    public function show(Meal $meal, MealRepository $mealRepository, $id): Response
    {
        $my = $mealRepository->find(['id' => $id]);
        $final = $my->getIngredients();
        $final = explode(',', $final);

        return $this->render('meal_user/show.html.twig', [
            'meal' => $meal,
            'ingredient' => $final,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_meal_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Meal $meal, MealRepository $mealRepository, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(Meal1Type::class, $meal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $currentpic = $meal->getPicture();
            $image = $form->get('picture')->getData();
            if ($image) {
                unlink($this->getParameter("image_directory") . $currentpic);
                $imageName = $fileUploader->upload($image);
                $meal->setPicture($imageName);
            }
            $mealRepository->save($meal, true);

            return $this->redirectToRoute('app_meal_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('meal_user/edit.html.twig', [
            'meal' => $meal,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_meal_user_delete')]
    public function delete(ManagerRegistry $doctrine, $id): Response
    {
        $em = $doctrine->getManager();
        $meal = $doctrine->getRepository(Meal::class)->find($id);
        $image = $meal->getPicture();
        if (file_exists($this->getParameter("image_directory") . $image)) {
            unlink($this->getParameter("image_directory") . $image);
        }

        $em->remove($meal);
        $em->flush();

        return $this->redirectToRoute('app_meal_user_index',);
    }

    // #[Route('/meal{id}/delete', name: 'app_meal_delete')]
    // public function delete(ManagerRegistry $doctrine, $id)
    // {
    //     $em = $doctrine->getManager();
    //     $meal = $doctrine->getRepository(Meal::class)->find($id);
    //     $image = $meal->getPicture();
    //     if (file_exists($this->getParameter("image_directory") . $image)) {
    //         unlink($this->getParameter("image_directory") . $image);
    //     }

    //     $em->remove($meal);
    //     $em->flush();

    //     return $this->redirectToRoute('app_meal_index');
    // }
}

templates/meal_user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<link href="{{ asset('css/newUserForm.css') }}" rel="stylesheet" type="text/css"/>
    
    <div>
    <button class="btn mybtn">{{ button_label|default('Save') }}</button>
    </div>
{{ form_end(form) }}

templates/meal_user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Meal{% endblock %}

{% block body %}
<link href="{{ asset('css/newUserForm.css') }}" rel="stylesheet" type="text/css"/>

        {# {% include "/components/navbar.html" %} #}
        <div class="container mt-5 myform   " style="border-radius: 12px;"> 
        <h1>Edit Meal</h1>
           {{ include('meal_user/_form.html.twig', {'button_label': 'Update'}) }}
             <a  class=" btn mybtn" href="{{ path('app_meal_user_index') }}">Meals</a>
        </div>
{% endblock %}

templates/meal_user/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link href="{{ asset('css/usermeal.css') }}" rel="stylesheet" type="text/css"/>

{% endblock %}


{% block title %}Meal index{% endblock %}

{% block body %}
{% include "components/navbar.html" %}

   

    <div class="container my-4">
    <h1 class="my-5 text-center myhead">Check the Recipes ....</h1 >
    <a class="mybtn" href="{{ path('app_meal_user_new') }}">Create new meal</a>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-1">
  
        {% for meal in meals %}
   
        <div class="col">
          <div class="card h-100">
            <a href="{{ path('app_meal_user_show', {'id': meal.id}) }}"><img src="../../uploads/{{ meal.picture }}" class="card-img-top img-fluid" alt="..."></a>
            <div class="card-body">
              <h5 class="card-title">{{ meal.name }}</h5>
              <p class="card-text">{{ meal.preparation }} <a href="{{ path('app_meal_user_show', {'id': meal.id}) }}">show more ...</a>.</p>
               </div>
            {# <div class="card-footer">
              <small class="text-muted"><td><img src="https://img.icons8.com/dotty/80/null/time.png"/>{{ meal.cookingTime }} Min</td></small>
              
            </div> #}
              <ul class="list-group">
    <li class="list-group-item list-group-item-success"><img src="https://img.icons8.com/dotty/80/null/time.png"/>{{ meal.cookingTime }} Min</li>
    <li class="list-group-item list-group-item-danger"><img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/null/external-calories-fitness-at-home-flaticons-lineal-color-flat-icons-2.png"/>{{ meal.calories }} Cal.</li>
  </ul>
          </div>       
        </div>
        {% endfor %}

        </tbody>

    </table>
          </div>       <br>
          </div>       

    

{% include "components/footer.html" %}
    
{% endblock %}

templates/meal_user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Meal{% endblock %}

{% block body %}
<link href="{{ asset('css/newUserForm.css') }}" rel="stylesheet" type="text/css"/>
        {# {% include "/components/navbar.html" %} #}
        <div class="container mt-5 myform">
            <h1><img src="../../pictures/chef.png" alt="chef">Create your Meal</h1>
            {{ include('meal_user/_form.html.twig') }}
        
       

             <a  class=" btn mybtn" href="{{ path('app_meal_user_index') }}">Meals</a>
        </div>
{% endblock %}

  

templates/meal_user/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link href="{{ asset('css/showusermeal.css') }}" rel="stylesheet" type="text/css"/>

{% endblock %}

{% block title %}Meal{% endblock %}

{% block body %}
        {% include "components/navbar.html" %}
        <br>
        <br>
        <br>
        <br>

{# <div class="container mt-5 w-50">
    <div class="d-flex">

            <img class="img-user-details" src="{{ asset('/uploads/' ~ meal.picture) }}" style="width: 25rem">

        
        <div>
            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ meal.id }}</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{ meal.name }}</td>
                    </tr>
                    <tr>
                        <th>Picture</th>
                    </tr>
                    <tr>
                        <th>Category</th>
                        <td>{{ meal.category }}</td>
                    </tr>
                    <tr>
                        <th>Calories</th>
                        <td>{{ meal.calories }}</td>
                    </tr>
                    <tr>
                        <th>Rating</th>
                        <td>{{ meal.rating }}</td>
                    </tr>
                    <tr>
                        <th>Preparation</th>
                        <td>{{ meal.preparation }}</td>
                    </tr>
                    <tr>
                        <th>Cooking_time</th>
                        <td>{{ meal.cookingTime }}</td>
                    </tr>
                    {% for ing in ingredient %}
                    <tr>
                        <th>Ingredients</th>
                        <td>{{ ing }}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
                
            </table>

    <a href="{{ path('app_meal_user_edit', {'id': meal.id}) }}">edit</a>
    </div>
</div> #}
<div class="container mt-4">

    <h1 class="hline">Recipe Card</h1>
    <div class="card mx-auto px-auto" >
  <img src="../../uploads/{{ meal.picture }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ meal.name }}</h5>
    <p class="card-text HMtext">{{ meal.preparation }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><img src="https://img.icons8.com/ios/40/null/category.png"/> <span class="bold-headers">Category:</span>{{ meal.category }}</li>
    <li class="list-group-item"><img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/40/null/external-calories-fitness-at-home-flaticons-lineal-color-flat-icons-2.png"/><span class="bold-headers">Calories:</span>{{ meal.calories }}</li>
    <li class="list-group-item"><img src="https://img.icons8.com/dotty/40/null/time.png"/><span class="bold-headers">Time:</span>{{ meal.cookingTime }}</li>
    <li class="list-group-item"><img src="https://img.icons8.com/external-outline-berkahicon/40/null/external-ingredient-linely-baking-outline-berkahicon.png"/><span class="bold-headers"> Ingredients:</span>{% for ing in ingredient %}
            
                
             <ul>
  <li>{{ ing }}</li>
</ul>  
            
            {% endfor %}</li>
  </ul>
  <div class="card-body">
    <a class="btn btn-warning" href="{{ path('app_meal_user_edit', {'id': meal.id}) }}" class="card-link"><img src="https://img.icons8.com/ios-filled/25/null/edit--v1.png"/>Edit</a>
    <button class="btn btn-danger" onclick="deleteswal('{{meal.id}}')"><img src="https://img.icons8.com/wired/25/null/filled-trash.png"/>Delete</button>
  </div>
</div>
    <div class="container d-flex p-5"><a class="btn btn-success mx-auto" href="{{ path('app_meal_user_index') }}"><img src="https://img.icons8.com/sf-regular-filled/50/null/circled-left--v2.png"/> back to list</a> </div>

        {% include "components/footer.html" %}

{% endblock %}
{% block js %}
    <script src='{{asset("js/userpage.js")}}'></script>
{% endblock %}