src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $fname = null;

    #[ORM\Column(length: 50)]
    private ?string $lname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_of_birth = null;

    #[ORM\Column(length: 50)]
    private ?string $phone = null;

    #[ORM\Column(length: 50)]
    private ?string $gender = null;

    #[ORM\Column]
    private ?bool $blocked = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'fk_user', targetEntity: Week::class)]
    private Collection $weeks;

    #[ORM\OneToMany(mappedBy: 'fk_user', targetEntity: Meal::class)]
    private Collection $meals;

    public function __construct()
    {
        $this->weeks = new ArrayCollection();
        $this->meals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function isBlocked(): ?bool
    {
        return $this->blocked;
    }

    public function setBlocked(bool $blocked): self
    {
        $this->blocked = $blocked;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Week>
     */
    public function getWeeks(): Collection
    {
        return $this->weeks;
    }

    public function addWeek(Week $week): self
    {
        if (!$this->weeks->contains($week)) {
            $this->weeks->add($week);
            $week->setFkUser($this);
        }

        return $this;
    }

    public function removeWeek(Week $week): self
    {
        if ($this->weeks->removeElement($week)) {
            // set the owning side to null (unless already changed)
            if ($week->getFkUser() === $this) {
                $week->setFkUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Meal>
     */
    public function getMeals(): Collection
    {
        return $this->meals;
    }

    public function addMeal(Meal $meal): self
    {
        if (!$this->meals->contains($meal)) {
            $this->meals->add($meal);
            $meal->setFkUser($this);
        }

        return $this;
    }

    public function removeMeal(Meal $meal): self
    {
        if ($this->meals->removeElement($meal)) {
            // set the owning side to null (unless already changed)
            if ($meal->getFkUser() === $this) {
                $meal->setFkUser(null);
            }
        }

        return $this;
    }
}

src/Controller/EditselfController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\User1Type;
use App\Form\User2Type;
use App\Repository\UserRepository;
use App\Service\FileUploader;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Http\Authenticator\Passport\Credentials\PasswordCredentials;

#[Route('/user')]
class EditselfController extends AbstractController
{
    #[Route('/info/{id}', name: 'app_editself_index', methods: ['GET'])]
    public function index(UserRepository $userRepository, $id): Response
    {
        return $this->render('editself/index.html.twig', [
            'users' => $userRepository->findBy(['id' => $id]),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_editself_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository, FileUploader $fileUploader, $id): Response
    {
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $currentpic = $user->getImage();
            $image = $form->get('image')->getData();
            if ($image) {
                unlink($this->getParameter("image_directory") . $currentpic);
                $imageName = $fileUploader->upload($image);
                $user->setImage($imageName);
            }
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_editself_index', ['id' => $id], Response::HTTP_SEE_OTHER);
        }

        return $this->render('editself/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/self{id}/delete', name: 'app_editself_delete')]
    public function delete(ManagerRegistry $doctrine, $id): Response
    {
        $em = $doctrine->getManager();
        $user = $doctrine->getRepository(User::class)->find($id);
        $image = $user->getImage();
        if (file_exists($this->getParameter("image_directory") . $image)) {
            unlink($this->getParameter("image_directory") . $image);
        }

        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute('app_login', []);
    }

    #[Route('/change/password', name: 'app_editself_change_password', methods: ['GET', 'POST'])]
    public function chnagePassword(Request $request, UserRepository $userRepository, FileUploader $fileUploader, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(User2Type::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);
            return $this->redirectToRoute('app_editself_index', ['id' => $user->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('editself/changepass.html.twig', [
            'user' => $user,
            'form2' => $form,
        ]);
    }

}

templates/editself/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/editself/_passwordform.html.twig
{{ form_start(form2) }}
    {{ form_widget(form2) }}
{{ form_end(form2) }}

templates/editself/changepass.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('css/newUserForm.css') }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body %}
<div class="container mt-5 myform   " style="border-radius: 12px;"> 
    <h1>Edit User</h1>
    {{ include('editself/_passwordform.html.twig', {'button_label': 'Update'}) }}
    <a class=" btn mybtn" href="{{ path('app_editself_index', {'id': user.id}) }}">Your Profile</a>
</div>


{% endblock %}

templates/editself/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('css/newUserForm.css') }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body %}
<div class="container mt-5 myform   " style="border-radius: 12px;"> 
    <h1>Edit User</h1>
    {{ include('editself/_form.html.twig', {'button_label': 'Update'}) }}
    <a class=" btn mybtn" href="{{ path('app_editself_index', {'id': user.id}) }}">Your Profile</a>
</div>


{% endblock %}

templates/editself/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}
{% block stylesheets %}
    <link href="{{ asset('css/userself.css') }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body %}
    <div class="container mycont">
        <div class="info">
            <div class="image-cont half">
                {% for user in users %}
                <img height="130px" width="215px"  src="{{asset("uploads/" ~ user.image)}}" alt="...">
                {% endfor %}
                
            </div>
            <div class="info-cont half">
                {% for user in users %}
                <div class="first">
                    <h4> {{user.fname ~ " " ~ user.lname}} </h4>
                    <a class="btn btn-success mybtn2" href="{{ path('app_editself_edit', {'id': user.id}) }}">Edit</a>
                </div>
                <div>
                    <p>Date of Birth: {{user.dateOfBirth ? user.dateOfBirth|date('Y-m-d') : ''}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Gender: {{ user.gender }} </p>
                    <hr>
                    <p><i class="fa-solid fa-phone"></i> &nbsp;&nbsp; {{ user.phone}}</p>
                    <p><i class="fa-solid fa-envelope"></i> &nbsp;&nbsp; {{ user.email}}</p>
                    <button onclick="deleteswal('{{user.id}}')" class="btn btn-danger mybtn2">Delete</button>
                    <a class="btn btn-success mybtn2" href="{{ path('app_home', {'id': user.id}) }}"> Back to Home</a>
                    <a class="btn btn-success mybtn2" href="{{ path('app_editself_change_password') }}">Change Password</a>


                </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src='{{asset("js/deleteYourProfile.js")}}'></script>
{% endblock %}